TRANSFER_EVAL:
  WANDB_PROJECT_NAME: "matthiasdelange/ContinualUserAdaptation"
  # Finetune SGD 0.01 plain
#  WANDB_GROUP_TO_EVAL: "Finetuning_2022-09-14_19-06-02_UID2c4355e2-c42c-46d9-ba37-8cb8abe8d1d0_MATT"
  # Final01_01
#  WANDB_GROUPS_TO_EVAL_CSV_PATH: "/home/matthiasdelange/sftp_remote_projects/ContextualOracle_Matthias/adhoc_results/wandb_export_2022-10-07T18_01_53.506-07_00.csv"
#  CSV_RANGE: (0,None) # DONE
#  CSV_RANGE: (7,14)
#  CSV_RANGE: (14,None)
  # Final02_01
#  WANDB_GROUPS_TO_EVAL_CSV_PATH: "/home/matthiasdelange/sftp_remote_projects/ContextualOracle_Matthias/adhoc_results/wandb_export_2022-10-09T10_50_16.573-07_00.csv"
#  CSV_RANGE: (0,4)
# Final02_01: Reservoir-action fix
#  WANDB_GROUPS_TO_EVAL_CSV_PATH: "/home/matthiasdelange/sftp_remote_projects/ContextualOracle_Matthias/adhoc_results/wandb_export_2022-10-18T13_56_51.654-07_00.csv"
  # Final03_01: fixed feats
#  WANDB_GROUPS_TO_EVAL_CSV_PATH: "/home/matthiasdelange/sftp_remote_projects/ContextualOracle_Matthias/adhoc_results/wandb_export_2022-10-09T11_23_33.094-07_00.csv"
  # Final03_02: fixed head
#  WANDB_GROUPS_TO_EVAL_CSV_PATH: "/home/matthiasdelange/sftp_remote_projects/ContextualOracle_Matthias/adhoc_results/wandb_export_2022-10-21T21_49_24.845-07_00.csv"
  # Final07_01: multi iter
#  WANDB_GROUPS_TO_EVAL_CSV_PATH: "/home/matthiasdelange/sftp_remote_projects/ContextualOracle_Matthias/adhoc_results/wandb_export_2022-10-09T12_10_59.286-07_00.csv"
#  CSV_RANGE: (0,None)
#  CSV_RANGE: (6,None)
#  CSV_RANGE: (8,None)
  # Final07_02: multi iter for 15-30
#  WANDB_GROUPS_TO_EVAL_CSV_PATH: "/home/matthiasdelange/sftp_remote_projects/ContextualOracle_Matthias/adhoc_results/wandb_export_2022-10-24T22_35_02.760-07_00.csv"
  # Final07_02: iter 50
#  WANDB_GROUP_TO_EVAL: "Finetuning_2022-10-26_05-22-31_UID761f3a32-39d2-4c49-a1e8-00446ff48982" # Iter 50
#  WANDB_GROUP_TO_EVAL: "Finetuning_2022-10-26_11-07-26_UID1d977d1e-2dfa-4f8b-8a45-da9337e6fc2f" # iter 25
  WANDB_GROUPS_TO_EVAL_CSV_PATH: "/home/matthiasdelange/sftp_remote_projects/ContextualOracle_Matthias/adhoc_results/wandb_export_2022-10-26T14_12_55.940-07_00.csv" # Remaining iters

# Final14_01: Replay head retrain 0.01
#  WANDB_GROUP_TO_EVAL: "Finetuning_2022-10-05_05-48-18_UID11ce17bb-0afa-46c7-8934-978c9a45ba6c"
# Final14_02: SGD head retrain 0.01
#  WANDB_GROUP_TO_EVAL: "Finetuning_2022-10-04_22-54-45_UID3861e638-75a4-4dee-9e89-2b6fb98f971a"

# Final11: Feat-classifier LR async SGD
#  WANDB_GROUPS_TO_EVAL_CSV_PATH: "/home/matthiasdelange/sftp_remote_projects/ContextualOracle_Matthias/adhoc_results/wandb_export_2022-10-20T12_50_20.021-07_00.csv"
#  CSV_RANGE: (0,4)
# Final17: Momentum async
#  WANDB_GROUPS_TO_EVAL_CSV_PATH: "/home/matthiasdelange/sftp_remote_projects/ContextualOracle_Matthias/adhoc_results/wandb_export_2022-10-20T12_41_20.072-07_00.csv"


  DIAGONAL_ONLY: True # Cartesian product or only user-model with same user-stream.
  INCLUDE_PRETRAIN_STREAM: False
  INCLUDE_PRETRAIN_MODEL: False # True if calculating OAG/HAG directly
  NUM_EXPECTED_USERS: 10

  PRETRAIN_REFERENCE_GROUP_WANDB: 'train' # or test
  PRETRAIN_TRAIN_USERS_GROUP_WANDB: "FixedNetwork_2022-10-07_21-50-23_UID80e71950-cea4-44ba-ba16-7dddfe95be26"
  PRETRAIN_TEST_USERS_GROUP_WANDB: "FixedNetwork_2022-10-07_15-23-09_UID6e87e600-a447-438f-9a31-f5cae6dc9ed4"

CHECKPOINT_LOAD_MODEL_HEAD: True
NUM_USERS_PER_DEVICE: 3 # Model-stream pairs in parallel on 1 device
GPU_IDS: None
NUM_GPUS: 1

PREDICT_PHASE:
  NUM_WORKERS: 8
  BATCH_SIZE: 10 # 10=5G/user

# Debug/fast run
FAST_DEV_RUN: False
FAST_DEV_DATA_CUTOFF: None
USER_SELECTION: None