TRANSFER_EVAL:
  WANDB_PROJECT_NAME: "matthiasdelange/ContinualUserAdaptation"
  WANDB_GROUP_TO_EVAL: "Finetuning_2022-09-19_12-16-57_UID11a32c82-471b-4921-a5c7-0ee393fdabf0"
  # TODO CSV to eval: Run all groups
  #  OUTPUT_DIR: ""
  DIAGONAL_ONLY: False # Cartesian product or only user-model with same user-stream.
  INCLUDE_PRETRAIN_STREAM: False
  INCLUDE_PRETRAIN_MODEL: True

CHECKPOINT_LOAD_MODEL_HEAD: True
NUM_USERS_PER_DEVICE: 10
GPU_IDS: None
NUM_GPUS: 1

PREDICT_PHASE:
  NUM_WORKERS: 10
  BATCH_SIZE: 20

FAST_DEV_RUN: False
FAST_DEV_DATA_CUTOFF: None