TRANSFER_EVAL:
  WANDB_PROJECT_NAME: "matthiasdelange/ContinualUserAdaptation"
  WANDB_GROUP_TO_EVAL: "Finetuning_2022-09-19_12-16-57_UID11a32c82-471b-4921-a5c7-0ee393fdabf0"
  OUTPUT_DIR: "pretrain"

CHECKPOINT_LOAD_MODEL_HEAD: True
NUM_USERS_PER_DEVICE: 1
GPU_IDS: None
NUM_GPUS: 1