TRANSFER_EVAL:
  WANDB_PROJECT_NAME: "matthiasdelange/ContinualUserAdaptation"
#  WANDB_GROUP_TO_EVAL: "IIDFinetuning_2022-10-05_10-21-39_UIDd7a7a88d-8017-4086-aacd-1b701aa07ef9"
# Eval 01_01
#  WANDB_GROUP_TO_EVAL: "Finetuning_2022-10-04_10-45-52_UID4ab309a3-d7cc-41f5-b763-333224d6bc07"
# Eval 02_01
#  WANDB_GROUPS_TO_EVAL_CSV_PATH:  "/home/matthiasdelange/sftp_remote_projects/ContextualOracle_Matthias/adhoc_results/wandb_export_2022-10-14T22_43_50.802-07_00.csv"
#  CSV_RANGE: (0,None)
#  CSV_RANGE: (1,None)
# Eval02_iter1: FIX reservoir-action
#  WANDB_GROUP_TO_EVAL: "Replay_2022-10-18_19-05-49_UID17119890-e6bf-4820-b1e9-087e841bea3c"
# Eval 03_01
#  WANDB_GROUP_TO_EVAL: "Finetuning_2022-10-14_13-11-14_UIDac6a2798-7fb0-4e9c-9896-c6c54de5237c"
# Eval 13_01
#  WANDB_GROUP_TO_EVAL: "IIDFinetuning_2022-10-05_10-21-39_UIDd7a7a88d-8017-4086-aacd-1b701aa07ef9"
# Eval 15_01
#  WANDB_GROUP_TO_EVAL: "Finetuning_2022-10-17_00-52-59_UIDeac059ad-de78-4db0-8f4a-47c3764df79e"
  # Eval 01/02/03
#  WANDB_GROUPS_TO_EVAL_CSV_PATH: "/home/matthiasdelange/sftp_remote_projects/ContextualOracle_Matthias/adhoc_results/wandb_export_2022-10-10T10_09_56.712-07_00.csv"
#  CSV_RANGE: (0,2)
#  CSV_RANGE: (2,4)
#  CSV_RANGE: (4,None)

# 10 ITER EXPS

# Eval01_iter10
#  WANDB_GROUP_TO_EVAL: "Finetuning_2022-10-17_21-40-08_UIDb58f58b4-dc8e-4865-80d6-7c62971ee12a"
# Eval03_iter10
#  WANDB_GROUP_TO_EVAL: "Finetuning_2022-10-17_21-48-58_UIDfd63e7e9-a8f8-4e12-973f-263737142a36"

# Eval02_iter10: Replay (reservoir stream 64)
#  WANDB_GROUP_TO_EVAL: "Replay_2022-10-18_15-14-08_UID5301dd1d-1172-4208-a415-143425e78dbe"

# Eval02_iter10: Replay (reservoir action 64) -> TODO
#  WANDB_GROUP_TO_EVAL: "Replay_2022-10-18_15-13-16_UIDf194b1d8-b810-4456-8865-b3092d7c5a71"

# Eval02_iter10: Replay (window 64) -> TODO
  WANDB_GROUP_TO_EVAL: "Replay_2022-10-18_15-12-47_UIDd54b728e-878d-4a24-aa58-67ebded4a311"

# Eval02_iter10: Full Replay (window infinity)
#  WANDB_GROUP_TO_EVAL: "Replay_2022-10-18_15-09-56_UID68dee416-bf2c-4ca6-a50a-796a6746f852"



# Eval13_iter10
#  WANDB_GROUP_TO_EVAL: "IIDFinetuning_2022-10-17_14-59-57_UID909a9e66-7616-416a-8c18-8aaec0d22478"



  DIAGONAL_ONLY: True # Cartesian product or only user-model with same user-stream.
  INCLUDE_PRETRAIN_STREAM: False
  INCLUDE_PRETRAIN_MODEL: False # True if calculating OAG/HAG directly
  NUM_EXPECTED_USERS: 40

  PRETRAIN_REFERENCE_GROUP_WANDB: 'test' # or test
  PRETRAIN_TRAIN_USERS_GROUP_WANDB: "FixedNetwork_2022-10-07_21-50-23_UID80e71950-cea4-44ba-ba16-7dddfe95be26"
  PRETRAIN_TEST_USERS_GROUP_WANDB: "FixedNetwork_2022-10-07_15-23-09_UID6e87e600-a447-438f-9a31-f5cae6dc9ed4"

CHECKPOINT_LOAD_MODEL_HEAD: True
NUM_USERS_PER_DEVICE: 3 # Model-stream pairs in parallel on 1 device
GPU_IDS: None
NUM_GPUS: 1

PREDICT_PHASE:
  NUM_WORKERS: 7
  BATCH_SIZE: 10 # 10=5G/user

# Debug/fast run
FAST_DEV_RUN: False
FAST_DEV_DATA_CUTOFF: None
USER_SELECTION: None