TRANSFER_EVAL:
  WANDB_PROJECT_NAME: "matthiasdelange/ContinualUserAdaptation"
  WANDB_GROUP_TO_EVAL: "IIDFinetuning_2022-10-05_10-21-39_UIDd7a7a88d-8017-4086-aacd-1b701aa07ef9"
#  WANDB_GROUPS_TO_EVAL_CSV_PATH: "/home/matthiasdelange/sftp_remote_projects/ContextualOracle_Matthias/adhoc_results/wandb_export_2022-10-04T20_30_12.351-07_00.csv"
  DIAGONAL_ONLY: True # Cartesian product or only user-model with same user-stream.
  INCLUDE_PRETRAIN_STREAM: False
  INCLUDE_PRETRAIN_MODEL: True
  NUM_EXPECTED_USERS: 40 # For test we expect 40 users

CHECKPOINT_LOAD_MODEL_HEAD: True
NUM_USERS_PER_DEVICE: 3 # Model-stream pairs in parallel on 1 device
GPU_IDS: None
NUM_GPUS: 1

PREDICT_PHASE:
  NUM_WORKERS: 8
  BATCH_SIZE: 40 # 10=5G/user

FAST_DEV_RUN: False
FAST_DEV_DATA_CUTOFF: None