CHECKPOINT_USER_ID: ""
CHECKPOINT_FILE_PATH: ""
METHOD:
  METHOD_NAME: "Finetuning"
TRAIN:
  ENABLE: True
  DATASET: Ego4dContinualRecognition
  BATCH_SIZE: 10 # Process 1 new video-subsequence a time (Online)
  CONTINUAL_EVAL_BATCH_SIZE: 50
  CONTINUAL_EVAL_FREQ: 1
DATA:
  USER_SUBSET: 'train' # train or test
  PATH_TO_DATA_SPLIT_JSON:
    TRAIN_SPLIT: '/home/matthiasdelange/sftp_remote_projects/ContextualOracle_Matthias/forecasting/continual_ego4d/usersplit_data/2022-07-15_14-59-55_ego4d_LTA_usersplit/ego4d_LTA_train_usersplit_40users.json'
    TEST_SPLIT: '//home/matthiasdelange/sftp_remote_projects/ContextualOracle_Matthias/forecasting/continual_ego4d/usersplit_data/2022-07-15_14-59-55_ego4d_LTA_usersplit/ego4d_LTA_test_usersplit_10users.json'
  SEQ_OBSERVED_FRAME_STRIDE: 1 # TODO constrain to BATCH SIZE to avoid overlap (Stride for next observed frame in stream
  TARGET_FPS: 30
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [ 256, 320 ]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [ 3, 3 ]
  TASK: "classification"
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 101
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [ [ 3, 3 ], [ 4, 4 ], [ 23, 23 ], [ 3, 3 ] ]
  SPATIAL_STRIDES: [ [ 1, 1 ], [ 2, 2 ], [ 2, 2 ], [ 2, 2 ] ]
  SPATIAL_DILATIONS: [ [ 1, 1 ], [ 1, 1 ], [ 1, 1 ], [ 1, 1 ] ]
NONLOCAL:
  LOCATION: [ [ [ ], [ ] ], [ [ ], [ ] ], [ [ ], [ ] ], [ [ ], [ ] ] ]
  GROUP: [ [ 1, 1 ], [ 1, 1 ], [ 1, 1 ], [ 1, 1 ] ]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 1e-4
  LR_POLICY: cosine_warmup
  MAX_EPOCH: 1
  MOMENTUM: 0.9
  OPTIMIZING_METHOD: sgd
  WEIGHT_DECAY: 1e-4
MODEL:
  NUM_CLASSES: [ 115, 478 ] # Verbs, nouns
  ARCH: slowfast
  MODEL_NAME: MultiTaskSlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
